In [1]:
from unidecode import unidecode
import pandas as pd
import numpy as np
import requests
from io import StringIO

In [4]:
url = 'https://fbref.com/en/comps/Big5/possession/players/Big-5-European-Leagues-Stats'
html_content = requests.get(url).text.replace('<!--', ' ').replace('-->', ' ')
df=pd.read_html(StringIO(html_content))

In [5]:
df

[   Unnamed: 0_level_0 Unnamed: 1_level_0 Touches                          \
      Competition Name                 MP Touches Def Pen Def 3rd Mid 3rd
 0       de Bundesliga                NaN   623.3    67.1   202.2   284.1
 1          es La Liga                NaN   586.3    61.2   191.4   265.9
 2          fr Ligue 1                NaN   605.2    62.1   193.2   278.6
 3  eng Premier League                NaN   600.4    68.5   200.0   252.1
 4          it Serie A                NaN   574.3    61.6   187.1   263.1

                          Take-Ons  ...            Carries                  \
   Att 3rd Att Pen   Live      Att  ... Tkld Tkld% Carries TotDist PrgDist
 0   142.2    22.4  623.1     15.8  ...  7.5  47.7   334.3  1651.6   816.0
 1   134.3    19.9  586.1     17.0  ...  7.9  46.4   317.7  1671.9   854.3
 2   139.3    21.5  605.0     18.9  ...  9.6  50.7   338.4  1757.7   900.9
 3   154.2    25.4  600.3     18.7  ...  8.3  44.3   341.6  1822.3   939.9
 4   129.6    19.5  574.2     14.9  ...  7.0  47.0   324.3  1746.0   883.9


    PrgC   1/3  CPA   Mis  Dis
 0  15.2  11.2  4.2  14.4  8.1
 1  16.0  11.5  4.3  14.9  8.5
 2  17.7  12.3  4.8  15.2  9.2
 3  19.0  12.7  6.3  13.1  9.8
 4  16.7  12.2  4.1  13.1  8.4

 [5 rows x 22 columns],
      Unnamed: 0_level_0 Unnamed: 1_level_0 Unnamed: 2_level_0  \
                      Rk             Player             Nation
 0                     1         Max Aarons            eng ENG
 1                     2     Rodrigo Abajas             es ESP
 2                     3     James Abankwah             ie IRL
 3                     4  Keyliane Abdallah             fr FRA
 4                     5   Yunis Abdelhamid             ma MAR
 ...                 ...                ...                ...
 2453               2360      Yanis Zouaoui             dz ALG
 2454               2361      Igor Zubeldia             es ESP
 2455               2362   Martín Zubimendi             es ESP
 2456               2363    Martin Ødegaard             no NOR
 2457               2364        Milan Đurić             ba BIH

      Unnamed: 3_level_0 Unnamed: 4_level_0  Unnamed: 5_level_0  \
                     Pos              Squad                Comp
 0                    DF        Bournemouth  eng Premier League
 1                    DF           Valencia          es La Liga
 2                    DF            Udinese          it Serie A
 3                    FW          Marseille          fr Ligue 1
 4                    DF      Saint-Étienne          fr Ligue 1
 ...                 ...                ...                 ...
 2453              FW,DF           Le Havre          fr Ligue 1
 2454                 DF      Real Sociedad          es La Liga
 2455                 MF      Real Sociedad          es La Liga
 2456                 MF            Arsenal  eng Premier League
 2457                 FW              Monza          it Serie A

      Unnamed: 6_level_0 Unnamed: 7_level_0 Unnamed: 8_level_0 Touches  ...  \
                     Age               Born                90s Touches  ...
 0                24-341               2000                0.2      21  ...
 1                21-212               2003                0.7      36  ...
 2                20-329               2004                0.2      18  ...
 3                18-249               2006                0.0       4  ...
 4                37-073               1987                9.4     524  ...
 ...                 ...                ...                ...     ...  ...
 2453             30-153               1994                1.9     124  ...
 2454             27-255               1997               13.4     922  ...
 2455             25-312               1999               15.0    1052  ...
 2456             25-359               1998                7.4     423  ...
 2457             34-202               1990               11.2     268  ...

      Carries                              Receiving      Unnamed: 31_level_0
      TotDist PrgDist PrgC 1/3 CPA Mis Dis       Rec PrgR             Matches
 0         74      35    1   0   0   0   0        15    3             Matches
 1        101      67    3   2   1   0   2        16    3             Matches
 2         59      35    1   0   0   0   1        10    0             Matches
 3         16       9    1   0   0   1   0         3    0             Matches
 4       1375     712    4   1   0   7   3       322    3             Matches
 ...      ...     ...  ...  ..  ..  ..  ..       ...  ...                 ...
 2453     389     242    5   6   0   4   3        61   11             Matches
 2454    3158    2093    9   4   0   4   1       638    2             Matches
 2455    2760    1313   24  16   2  19   9       708   24             Matches
 2456    1809     868   24  18   8  10  18       342   41             Matches
 2457     281     102    2   1   1  13  12       214   17             Matches

 [2458 rows x 32 columns]]

In [6]:
len(df)

2

In [7]:
df[1]

     Unnamed: 0_level_0 Unnamed: 1_level_0 Unnamed: 2_level_0  \
                     Rk             Player             Nation
0                     1         Max Aarons            eng ENG
1                     2     Rodrigo Abajas             es ESP
2                     3     James Abankwah             ie IRL
3                     4  Keyliane Abdallah             fr FRA
4                     5   Yunis Abdelhamid             ma MAR
...                 ...                ...                ...
2453               2360      Yanis Zouaoui             dz ALG
2454               2361      Igor Zubeldia             es ESP
2455               2362   Martín Zubimendi             es ESP
2456               2363    Martin Ødegaard             no NOR
2457               2364        Milan Đurić             ba BIH

     Unnamed: 3_level_0 Unnamed: 4_level_0  Unnamed: 5_level_0  \
                    Pos              Squad                Comp
0                    DF        Bournemouth  eng Premier League
1                    DF           Valencia          es La Liga
2                    DF            Udinese          it Serie A
3                    FW          Marseille          fr Ligue 1
4                    DF      Saint-Étienne          fr Ligue 1
...                 ...                ...                 ...
2453              FW,DF           Le Havre          fr Ligue 1
2454                 DF      Real Sociedad          es La Liga
2455                 MF      Real Sociedad          es La Liga
2456                 MF            Arsenal  eng Premier League
2457                 FW              Monza          it Serie A

     Unnamed: 6_level_0 Unnamed: 7_level_0 Unnamed: 8_level_0 Touches  ...  \
                    Age               Born                90s Touches  ...
0                24-341               2000                0.2      21  ...
1                21-212               2003                0.7      36  ...
2                20-329               2004                0.2      18  ...
3                18-249               2006                0.0       4  ...
4                37-073               1987                9.4     524  ...
...                 ...                ...                ...     ...  ...
2453             30-153               1994                1.9     124  ...
2454             27-255               1997               13.4     922  ...
2455             25-312               1999               15.0    1052  ...
2456             25-359               1998                7.4     423  ...
2457             34-202               1990               11.2     268  ...

     Carries                              Receiving      Unnamed: 31_level_0
     TotDist PrgDist PrgC 1/3 CPA Mis Dis       Rec PrgR             Matches
0         74      35    1   0   0   0   0        15    3             Matches
1        101      67    3   2   1   0   2        16    3             Matches
2         59      35    1   0   0   0   1        10    0             Matches
3         16       9    1   0   0   1   0         3    0             Matches
4       1375     712    4   1   0   7   3       322    3             Matches
...      ...     ...  ...  ..  ..  ..  ..       ...  ...                 ...
2453     389     242    5   6   0   4   3        61   11             Matches
2454    3158    2093    9   4   0   4   1       638    2             Matches
2455    2760    1313   24  16   2  19   9       708   24             Matches
2456    1809     868   24  18   8  10  18       342   41             Matches
2457     281     102    2   1   1  13  12       214   17             Matches

[2458 rows x 32 columns]

In [8]:
df[1].columns = df[1].columns.droplevel(0)

In [9]:
df[1]

,Rk,Player,Nation,Pos,Squad,Comp,Age,Born,90s,Touches,...,TotDist,PrgDist,PrgC,1/3,CPA,Mis,Dis,Rec,PrgR,Matches
0,1,Max Aarons,eng ENG,DF,Bournemouth,eng Premier League,24-341,2000,0.2,21,...,74,35,1,0,0,0,0,15,3,Matches
1,2,Rodrigo Abajas,es ESP,DF,Valencia,es La Liga,21-212,2003,0.7,36,...,101,67,3,2,1,0,2,16,3,Matches
2,3,James Abankwah,ie IRL,DF,Udinese,it Serie A,20-329,2004,0.2,18,...,59,35,1,0,0,0,1,10,0,Matches
3,4,Keyliane Abdallah,fr FRA,FW,Marseille,fr Ligue 1,18-249,2006,0.0,4,...,16,9,1,0,0,1,0,3,0,Matches
4,5,Yunis Abdelhamid,ma MAR,DF,Saint-Étienne,fr Ligue 1,37-073,1987,9.4,524,...,1375,712,4,1,0,7,3,322,3,Matches
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2453,2360,Yanis Zouaoui,dz ALG,"FW,DF",Le Havre,fr Ligue 1,30-153,1994,1.9,124,...,389,242,5,6,0,4,3,61,11,Matches
2454,2361,Igor Zubeldia,es ESP,DF,Real Sociedad,es La Liga,27-255,1997,13.4,922,...,3158,2093,9,4,0,4,1,638,2,Matches
2455,2362,Martín Zubimendi,es ESP,MF,Real Sociedad,es La Liga,25-312,1999,15.0,1052,...,2760,1313,24,16,2,19,9,708,24,Matches
2456,2363,Martin Ødegaard,no NOR,MF,Arsenal,eng Premier League,25-359,1998,7.4,423,...,1809,868,24,18,8,10,18,342,41,Matches
2457,2364,Milan Đurić,ba BIH,FW,Monza,it Serie A,34-202,1990,11.2,268,...,281,102,2,1,1,13,12,214,17,Matches

In [10]:
dfdata = df[1]

In [11]:
dfdata.head()

,Rk,Player,Nation,Pos,Squad,Comp,Age,Born,90s,Touches,...,TotDist,PrgDist,PrgC,1/3,CPA,Mis,Dis,Rec,PrgR,Matches
0,1,Max Aarons,eng ENG,DF,Bournemouth,eng Premier League,24-341,2000,0.2,21,...,74,35,1,0,0,0,0,15,3,Matches
1,2,Rodrigo Abajas,es ESP,DF,Valencia,es La Liga,21-212,2003,0.7,36,...,101,67,3,2,1,0,2,16,3,Matches
2,3,James Abankwah,ie IRL,DF,Udinese,it Serie A,20-329,2004,0.2,18,...,59,35,1,0,0,0,1,10,0,Matches
3,4,Keyliane Abdallah,fr FRA,FW,Marseille,fr Ligue 1,18-249,2006,0.0,4,...,16,9,1,0,0,1,0,3,0,Matches
4,5,Yunis Abdelhamid,ma MAR,DF,Saint-Étienne,fr Ligue 1,37-073,1987,9.4,524,...,1375,712,4,1,0,7,3,322,3,Matches

In [12]:
len(dfdata[dfdata.Age == 'Age'])

94

In [14]:
dfpossession = dfdata.drop(dfdata[dfdata.Age == 'Age'].index)

In [15]:
dfpossession.shape

(2364, 32)

In [16]:
dfpossession.columns

Index(['Rk', 'Player', 'Nation', 'Pos', 'Squad', 'Comp', 'Age', 'Born', '90s',
       'Touches', 'Def Pen', 'Def 3rd', 'Mid 3rd', 'Att 3rd', 'Att Pen',
       'Live', 'Att', 'Succ', 'Succ%', 'Tkld', 'Tkld%', 'Carries', 'TotDist',
       'PrgDist', 'PrgC', '1/3', 'CPA', 'Mis', 'Dis', 'Rec', 'PrgR',
       'Matches'],
      dtype='object')

In [17]:
dfpossession['90s'] = dfpossession['90s'].astype(float)
dfpossession['Touches'] = dfpossession['Touches'].astype(float)
dfpossession['Def Pen'] = dfpossession['Def Pen'].astype(float)
dfpossession['Def 3rd'] = dfpossession['Def 3rd'].astype(float)
dfpossession['Mid 3rd'] = dfpossession['Mid 3rd'].astype(float)
dfpossession['Att 3rd'] = dfpossession['Att 3rd'].astype(float)
dfpossession['Att Pen'] = dfpossession['Att Pen'].astype(float)
dfpossession['Live'] = dfpossession['Live'].astype(float)
dfpossession['Att'] = dfpossession['Att'].astype(float)
dfpossession['Succ'] = dfpossession['Succ'].astype(float)
dfpossession['Succ%'] = dfpossession['Succ%'].astype(float)
dfpossession['Tkld'] = dfpossession['Tkld'].astype(float)
dfpossession['Tkld%'] = dfpossession['Tkld%'].astype(float)
dfpossession['Carries'] = dfpossession['Carries'].astype(float)
dfpossession['TotDist'] = dfpossession['TotDist'].astype(float)
dfpossession['PrgDist'] = dfpossession['PrgDist'].astype(float)
dfpossession['PrgC'] = dfpossession['PrgC'].astype(float)
dfpossession['1/3'] = dfpossession['1/3'].astype(float)
dfpossession['CPA'] = dfpossession['CPA'].astype(float)
dfpossession['Mis'] = dfpossession['Mis'].astype(float)
dfpossession['Dis'] = dfpossession['Dis'].astype(float)
dfpossession['Rec'] = dfpossession['Rec'].astype(float)
dfpossession['PrgR'] = dfpossession['PrgR'].astype(float)

In [18]:
dfpossession['Touches'] = dfpossession['Touches'] / dfpossession['90s']
dfpossession['Def Pen'] = dfpossession['Def Pen'] / dfpossession['90s']
dfpossession['Def 3rd'] = dfpossession['Def 3rd'] / dfpossession['90s']
dfpossession['Mid 3rd'] = dfpossession['Mid 3rd'] / dfpossession['90s']
dfpossession['Att 3rd'] = dfpossession['Att 3rd'] / dfpossession['90s']
dfpossession['Att Pen'] = dfpossession['Att Pen'] / dfpossession['90s']
dfpossession['Live'] = dfpossession['Live'] / dfpossession['90s']
dfpossession['Att'] = dfpossession['Att'] / dfpossession['90s']
dfpossession['Succ'] = dfpossession['Succ'] / dfpossession['90s']
dfpossession['Tkld'] = dfpossession['Tkld'] / dfpossession['90s']
dfpossession['Carries'] = dfpossession['Carries'] / dfpossession['90s']
dfpossession['TotDist'] = dfpossession['TotDist'] / dfpossession['90s']
dfpossession['PrgDist'] = dfpossession['PrgDist'] / dfpossession['90s']
dfpossession['PrgC'] = dfpossession['PrgC'] / dfpossession['90s']
dfpossession['1/3'] = dfpossession['1/3'] / dfpossession['90s']
dfpossession['CPA'] = dfpossession['CPA'] / dfpossession['90s']
dfpossession['Mis'] = dfpossession['Mis'] / dfpossession['90s']
dfpossession['Dis'] = dfpossession['Dis'] / dfpossession['90s']
dfpossession['Rec'] = dfpossession['Rec'] / dfpossession['90s']
dfpossession['PrgR'] = dfpossession['PrgR'] / dfpossession['90s']

In [19]:
dfpossession.head()

,Rk,Player,Nation,Pos,Squad,Comp,Age,Born,90s,Touches,...,TotDist,PrgDist,PrgC,1/3,CPA,Mis,Dis,Rec,PrgR,Matches
0,1,Max Aarons,eng ENG,DF,Bournemouth,eng Premier League,24-341,2000,0.2,105.000000,...,370.000000,175.000000,5.000000,0.000000,0.000000,0.000000,0.000000,75.000000,15.000000,Matches
1,2,Rodrigo Abajas,es ESP,DF,Valencia,es La Liga,21-212,2003,0.7,51.428571,...,144.285714,95.714286,4.285714,2.857143,1.428571,0.000000,2.857143,22.857143,4.285714,Matches
2,3,James Abankwah,ie IRL,DF,Udinese,it Serie A,20-329,2004,0.2,90.000000,...,295.000000,175.000000,5.000000,0.000000,0.000000,0.000000,5.000000,50.000000,0.000000,Matches
3,4,Keyliane Abdallah,fr FRA,FW,Marseille,fr Ligue 1,18-249,2006,0.0,inf,...,inf,inf,inf,NaN,NaN,inf,NaN,inf,NaN,Matches
4,5,Yunis Abdelhamid,ma MAR,DF,Saint-Étienne,fr Ligue 1,37-073,1987,9.4,55.744681,...,146.276596,75.744681,0.425532,0.106383,0.000000,0.744681,0.319149,34.255319,0.319149,Matches

In [22]:
dfpossession['PlSqu'] = dfpossession['Player'] + dfpossession['Squad']

In [24]:
dfpossession['Player'] = dfpossession['Player'].apply(unidecode)

In [25]:
dfpossession['Squad'] = dfpossession['Squad'].apply(unidecode)

In [26]:
dfpossession.to_excel('/Users/jamescorbett/Downloads/fbrefpossession_per90.xlsx', index=False)