In [1]:
from unidecode import unidecode
import pandas as pd
import numpy as np
import requests
from io import StringIO

In [5]:
url = 'https://fbref.com/en/comps/Big5/shooting/players/Big-5-European-Leagues-Stats'
html_content = requests.get(url).text.replace('<!--', ' ').replace('-->', ' ')
df=pd.read_html(StringIO(html_content))

In [6]:
df

[   Unnamed: 0_level_0 Unnamed: 1_level_0 Standard                           \
      Competition Name                 MP      Gls     Sh   SoT  SoT%  G/Sh
 0       de Bundesliga                NaN     1.62  13.17  4.47  33.9  0.11
 1          es La Liga                NaN     1.27  11.44  3.70  32.3  0.10
 2          fr Ligue 1                NaN     1.42  12.05  4.38  36.3  0.10
 3  eng Premier League                NaN     1.45  13.18  4.51  34.2  0.10
 4          it Serie A                NaN     1.32  12.29  3.83  31.2  0.10

                                 Expected
   G/SoT  Dist    FK    PK PKatt       xG  npxG npxG/Sh  G-xG np:G-xG
 0  0.34  17.0  0.36  0.10  0.16     1.46  1.34    0.10  0.12    0.15
 1  0.31  17.9  0.36  0.14  0.16     1.27  1.14    0.10 -0.02   -0.03
 2  0.28  17.2  0.33  0.17  0.21     1.45  1.29    0.11 -0.06   -0.07
 3  0.30  16.6  0.34  0.08  0.11     1.47  1.39    0.11 -0.05   -0.05
 4  0.31  17.7  0.39  0.13  0.18     1.26  1.13    0.09  0.03    0.04  ,
      Unnamed: 0_level_0 Unnamed: 1_level_0 Unnamed: 2_level_0  \
                      Rk             Player             Nation
 0                     1         Max Aarons            eng ENG
 1                     2     Rodrigo Abajas             es ESP
 2                     3     James Abankwah             ie IRL
 3                     4  Keyliane Abdallah             fr FRA
 4                     5   Yunis Abdelhamid             ma MAR
 ...                 ...                ...                ...
 2499               2404      Yanis Zouaoui             dz ALG
 2500               2405      Igor Zubeldia             es ESP
 2501               2406   Martín Zubimendi             es ESP
 2502               2407    Martin Ødegaard             no NOR
 2503               2408        Milan Đurić             ba BIH

      Unnamed: 3_level_0 Unnamed: 4_level_0  Unnamed: 5_level_0  \
                     Pos              Squad                Comp
 0                    DF        Bournemouth  eng Premier League
 1                    DF           Valencia          es La Liga
 2                 DF,MF            Udinese          it Serie A
 3                    FW          Marseille          fr Ligue 1
 4                    DF      Saint-Étienne          fr Ligue 1
 ...                 ...                ...                 ...
 2499              DF,FW           Le Havre          fr Ligue 1
 2500                 DF      Real Sociedad          es La Liga
 2501                 MF      Real Sociedad          es La Liga
 2502                 MF            Arsenal  eng Premier League
 2503                 FW              Monza          it Serie A

      Unnamed: 6_level_0 Unnamed: 7_level_0 Unnamed: 8_level_0 Standard  ...  \
                     Age               Born                90s      Gls  ...
 0                24-364               2000                1.0        0  ...
 1                21-235               2003                0.7        0  ...
 2                20-352               2004                1.0        0  ...
 3                18-272               2006                0.0        0  ...
 4                37-096               1987               10.4        0  ...
 ...                 ...                ...                ...      ...  ...
 2499             30-176               1994                2.6        0  ...
 2500             27-278               1997               15.4        0  ...
 2501             25-335               1999               16.0        1  ...
 2502             26-016               1998               11.0        1  ...
 2503             34-225               1990               12.6        4  ...

                        Expected                            Unnamed: 26_level_0
       Dist FK PK PKatt       xG npxG npxG/Sh  G-xG np:G-xG             Matches
 0      NaN  0  0     0      0.0  0.0     NaN   0.0     0.0             Matches
 1     24.5  0  0     0      0.1  0.1    0.07  -0.1    -0.1             Matches
 2     15.0  0  0     0      0.1  0.1    0.06  -0.1    -0.1             Matches
 3      NaN  0  0     0      0.0  0.0     NaN   0.0     0.0             Matches
 4     10.8  0  0     0      0.2  0.2    0.12  -0.2    -0.2             Matches
 ...    ... .. ..   ...      ...  ...     ...   ...     ...                 ...
 2499   NaN  0  0     0      0.0  0.0     NaN   0.0     0.0             Matches
 2500  21.4  0  0     0      0.1  0.1    0.02  -0.1    -0.1             Matches
 2501  14.6  0  0     0      1.5  1.5    0.12  -0.5    -0.5             Matches
 2502  18.5  1  1     1      2.5  1.7    0.10  -1.5    -1.7             Matches
 2503  11.3  0  0     0      2.7  2.7    0.13  +1.3    +1.3             Matches

 [2504 rows x 27 columns]]

In [7]:
len(df)

2

In [8]:
df[1]

     Unnamed: 0_level_0 Unnamed: 1_level_0 Unnamed: 2_level_0  \
                     Rk             Player             Nation
0                     1         Max Aarons            eng ENG
1                     2     Rodrigo Abajas             es ESP
2                     3     James Abankwah             ie IRL
3                     4  Keyliane Abdallah             fr FRA
4                     5   Yunis Abdelhamid             ma MAR
...                 ...                ...                ...
2499               2404      Yanis Zouaoui             dz ALG
2500               2405      Igor Zubeldia             es ESP
2501               2406   Martín Zubimendi             es ESP
2502               2407    Martin Ødegaard             no NOR
2503               2408        Milan Đurić             ba BIH

     Unnamed: 3_level_0 Unnamed: 4_level_0  Unnamed: 5_level_0  \
                    Pos              Squad                Comp
0                    DF        Bournemouth  eng Premier League
1                    DF           Valencia          es La Liga
2                 DF,MF            Udinese          it Serie A
3                    FW          Marseille          fr Ligue 1
4                    DF      Saint-Étienne          fr Ligue 1
...                 ...                ...                 ...
2499              DF,FW           Le Havre          fr Ligue 1
2500                 DF      Real Sociedad          es La Liga
2501                 MF      Real Sociedad          es La Liga
2502                 MF            Arsenal  eng Premier League
2503                 FW              Monza          it Serie A

     Unnamed: 6_level_0 Unnamed: 7_level_0 Unnamed: 8_level_0 Standard  ...  \
                    Age               Born                90s      Gls  ...
0                24-364               2000                1.0        0  ...
1                21-235               2003                0.7        0  ...
2                20-352               2004                1.0        0  ...
3                18-272               2006                0.0        0  ...
4                37-096               1987               10.4        0  ...
...                 ...                ...                ...      ...  ...
2499             30-176               1994                2.6        0  ...
2500             27-278               1997               15.4        0  ...
2501             25-335               1999               16.0        1  ...
2502             26-016               1998               11.0        1  ...
2503             34-225               1990               12.6        4  ...

                       Expected                            Unnamed: 26_level_0
      Dist FK PK PKatt       xG npxG npxG/Sh  G-xG np:G-xG             Matches
0      NaN  0  0     0      0.0  0.0     NaN   0.0     0.0             Matches
1     24.5  0  0     0      0.1  0.1    0.07  -0.1    -0.1             Matches
2     15.0  0  0     0      0.1  0.1    0.06  -0.1    -0.1             Matches
3      NaN  0  0     0      0.0  0.0     NaN   0.0     0.0             Matches
4     10.8  0  0     0      0.2  0.2    0.12  -0.2    -0.2             Matches
...    ... .. ..   ...      ...  ...     ...   ...     ...                 ...
2499   NaN  0  0     0      0.0  0.0     NaN   0.0     0.0             Matches
2500  21.4  0  0     0      0.1  0.1    0.02  -0.1    -0.1             Matches
2501  14.6  0  0     0      1.5  1.5    0.12  -0.5    -0.5             Matches
2502  18.5  1  1     1      2.5  1.7    0.10  -1.5    -1.7             Matches
2503  11.3  0  0     0      2.7  2.7    0.13  +1.3    +1.3             Matches

[2504 rows x 27 columns]

In [9]:
df[1].columns = df[1].columns.droplevel(0)

In [10]:
df[1]

,Rk,Player,Nation,Pos,Squad,Comp,Age,Born,90s,Gls,...,Dist,FK,PK,PKatt,xG,npxG,npxG/Sh,G-xG,np:G-xG,Matches
0,1,Max Aarons,eng ENG,DF,Bournemouth,eng Premier League,24-364,2000,1.0,0,...,NaN,0,0,0,0.0,0.0,NaN,0.0,0.0,Matches
1,2,Rodrigo Abajas,es ESP,DF,Valencia,es La Liga,21-235,2003,0.7,0,...,24.5,0,0,0,0.1,0.1,0.07,-0.1,-0.1,Matches
2,3,James Abankwah,ie IRL,"DF,MF",Udinese,it Serie A,20-352,2004,1.0,0,...,15.0,0,0,0,0.1,0.1,0.06,-0.1,-0.1,Matches
3,4,Keyliane Abdallah,fr FRA,FW,Marseille,fr Ligue 1,18-272,2006,0.0,0,...,NaN,0,0,0,0.0,0.0,NaN,0.0,0.0,Matches
4,5,Yunis Abdelhamid,ma MAR,DF,Saint-Étienne,fr Ligue 1,37-096,1987,10.4,0,...,10.8,0,0,0,0.2,0.2,0.12,-0.2,-0.2,Matches
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2499,2404,Yanis Zouaoui,dz ALG,"DF,FW",Le Havre,fr Ligue 1,30-176,1994,2.6,0,...,NaN,0,0,0,0.0,0.0,NaN,0.0,0.0,Matches
2500,2405,Igor Zubeldia,es ESP,DF,Real Sociedad,es La Liga,27-278,1997,15.4,0,...,21.4,0,0,0,0.1,0.1,0.02,-0.1,-0.1,Matches
2501,2406,Martín Zubimendi,es ESP,MF,Real Sociedad,es La Liga,25-335,1999,16.0,1,...,14.6,0,0,0,1.5,1.5,0.12,-0.5,-0.5,Matches
2502,2407,Martin Ødegaard,no NOR,MF,Arsenal,eng Premier League,26-016,1998,11.0,1,...,18.5,1,1,1,2.5,1.7,0.10,-1.5,-1.7,Matches
2503,2408,Milan Đurić,ba BIH,FW,Monza,it Serie A,34-225,1990,12.6,4,...,11.3,0,0,0,2.7,2.7,0.13,+1.3,+1.3,Matches

In [11]:
dfdata = df[1]

In [12]:
dfdata.head()

,Rk,Player,Nation,Pos,Squad,Comp,Age,Born,90s,Gls,...,Dist,FK,PK,PKatt,xG,npxG,npxG/Sh,G-xG,np:G-xG,Matches
0,1,Max Aarons,eng ENG,DF,Bournemouth,eng Premier League,24-364,2000,1.0,0,...,NaN,0,0,0,0.0,0.0,NaN,0.0,0.0,Matches
1,2,Rodrigo Abajas,es ESP,DF,Valencia,es La Liga,21-235,2003,0.7,0,...,24.5,0,0,0,0.1,0.1,0.07,-0.1,-0.1,Matches
2,3,James Abankwah,ie IRL,"DF,MF",Udinese,it Serie A,20-352,2004,1.0,0,...,15.0,0,0,0,0.1,0.1,0.06,-0.1,-0.1,Matches
3,4,Keyliane Abdallah,fr FRA,FW,Marseille,fr Ligue 1,18-272,2006,0.0,0,...,NaN,0,0,0,0.0,0.0,NaN,0.0,0.0,Matches
4,5,Yunis Abdelhamid,ma MAR,DF,Saint-Étienne,fr Ligue 1,37-096,1987,10.4,0,...,10.8,0,0,0,0.2,0.2,0.12,-0.2,-0.2,Matches

In [13]:
len(dfdata[dfdata.Age == 'Age'

96

In [14]:
dfshooting = dfdata.drop(dfdata[dfdata.Age == 'Age'].index)

In [15]:
dfshooting.shape

(2408, 27)

In [16]:
dfshooting.columns

Index(['Rk', 'Player', 'Nation', 'Pos', 'Squad', 'Comp', 'Age', 'Born', '90s',
       'Gls', 'Sh', 'SoT', 'SoT%', 'Sh/90', 'SoT/90', 'G/Sh', 'G/SoT', 'Dist',
       'FK', 'PK', 'PKatt', 'xG', 'npxG', 'npxG/Sh', 'G-xG', 'np:G-xG',
       'Matches'],
      dtype='object')

In [18]:
dfshooting['90s'] = dfshooting['90s'].astype(float)
dfshooting['Gls'] = dfshooting['Gls'].astype(float)
dfshooting['Sh'] = dfshooting['Sh'].astype(float)
dfshooting['SoT'] = dfshooting['SoT'].astype(float)
dfshooting['SoT%'] = dfshooting['SoT%'].astype(float)
dfshooting['G/Sh'] = dfshooting['G/Sh'].astype(float)
dfshooting['G/SoT'] = dfshooting['G/SoT'].astype(float)
dfshooting['Dist'] = dfshooting['Dist'].astype(float)
dfshooting['FK'] = dfshooting['FK'].astype(float)
dfshooting['PK'] = dfshooting['PK'].astype(float)
dfshooting['PKatt'] = dfshooting['PKatt'].astype(float)
dfshooting['xG'] = dfshooting['xG'].astype(float)
dfshooting['npxG'] = dfshooting['npxG'].astype(float)
dfshooting['npxG/Sh'] = dfshooting['npxG/Sh'].astype(float)
dfshooting['G-xG'] = dfshooting['G-xG'].astype(float)
dfshooting['np:G-xG'] = dfshooting['np:G-xG'].astype(float)

In [19]:
dfshooting['Gls'] = dfshooting['Gls'] / dfshooting['90s']
dfshooting['Sh'] = dfshooting['Sh'] / dfshooting['90s']
dfshooting['SoT'] = dfshooting['SoT'] / dfshooting['90s']
dfshooting['G/Sh'] = dfshooting['G/Sh'] / dfshooting['90s']
dfshooting['G/SoT'] = dfshooting['G/SoT'] / dfshooting['90s']
dfshooting['Dist'] = dfshooting['Dist'] / dfshooting['90s']
dfshooting['FK'] = dfshooting['FK'] / dfshooting['90s']
dfshooting['PK'] = dfshooting['PK'] / dfshooting['90s']
dfshooting['PKatt'] = dfshooting['PKatt'] / dfshooting['90s']
dfshooting['xG'] = dfshooting['xG'] / dfshooting['90s']
dfshooting['npxG'] = dfshooting['npxG'] / dfshooting['90s']
dfshooting['npxG/Sh'] = dfshooting['npxG/Sh'] / dfshooting['90s']
dfshooting['G-xG'] = dfshooting['G-xG'] / dfshooting['90s']
dfshooting['np:G-xG'] = dfshooting['np:G-xG'] / dfshooting['90s']

In [20]:
dfshooting['PlSqu'] = dfshooting['Player'] + dfshooting['Squad']

In [21]:
dfshooting['Player'] = dfshooting['Player'].apply(unidecode)

In [22]:
dfshooting['Squad'] = dfshooting['Squad'].apply(unidecode)

In [23]:
dfshooting.head()

,Rk,Player,Nation,Pos,Squad,Comp,Age,Born,90s,Gls,...,FK,PK,PKatt,xG,npxG,npxG/Sh,G-xG,np:G-xG,Matches,PlSqu
0,1,Max Aarons,eng ENG,DF,Bournemouth,eng Premier League,24-364,2000,1.0,0.0,...,0.0,0.0,0.0,0.000000,0.000000,NaN,0.000000,0.000000,Matches,Max AaronsBournemouth
1,2,Rodrigo Abajas,es ESP,DF,Valencia,es La Liga,21-235,2003,0.7,0.0,...,0.0,0.0,0.0,0.142857,0.142857,0.100000,-0.142857,-0.142857,Matches,Rodrigo AbajasValencia
2,3,James Abankwah,ie IRL,"DF,MF",Udinese,it Serie A,20-352,2004,1.0,0.0,...,0.0,0.0,0.0,0.100000,0.100000,0.060000,-0.100000,-0.100000,Matches,James AbankwahUdinese
3,4,Keyliane Abdallah,fr FRA,FW,Marseille,fr Ligue 1,18-272,2006,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Matches,Keyliane AbdallahMarseille
4,5,Yunis Abdelhamid,ma MAR,DF,Saint-Etienne,fr Ligue 1,37-096,1987,10.4,0.0,...,0.0,0.0,0.0,0.019231,0.019231,0.011538,-0.019231,-0.019231,Matches,Yunis AbdelhamidSaint-Étienne

In [24]:
dfshooting.to_excel('/Users/jamescorbett/Downloads/fbrefshooting_per90.xlsx', index=False)